version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Install awscli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
      - run:
        name: Set AWS credentials
        command: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_KEY" >> ~/.aws/config
workflows:
    build-and-test:
      jobs:
        - deploy

# version: 2
# jobs:
#   deploy:
#     docker:
#       - image: circleci/node:10
#     steps:
#       - checkout
    
   

#       - run:
#         name: Install awscli
#         command: |
#           sudo pip install awsebcli --upgrade
#       - run:
#         name: Create AWS credentials manually
#         command: |
#           mkdir ~/.aws
#           touch ~/.aws/config
#           chmod 600 ~/.aws/config
#           echo "[profile eb-cli]" > ~/.aws/config
#           echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
#           echo "aws_secret_access_key=$AWS_SECRET_KEY" >> ~/.aws/config
#       - run:
#         name: Deploy to EB if branch is Master
#         command: |
#           eb use server-backend-env --profile eb-cli
#           eb deploy -v --staged --profile eb-cli

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - deploy
        # filters:
        #   branches:
        #     only:
        #       - master
